title: Geha Group
website: https://jguerra-astro.github.io
baseurl: "/testing"
collections:
  pi:
    output: true
  postdocs:
    output: true
  grads:
    output: true
  undergrads:
    output: true
  pastmembers:
    output: true
  research:
    output: true
  outreach:
    output: true

sass:
  sass_dir: _sass
  style: compressed # or 'expanded' for development


plugins:
  - jekyll-scholar
scholar:
  sort_by: year, month
  order: descending
  bibliography_template: bib
  source: scripts
  bibliography: most_recent_all.bib